feat(test): add e2e test for timeout on config
Topsort/topsort.js pull request #28
Opened 2024-07-31 09:50 UTC by barbmarcio

This PR adds an E2E test to simulate timeout being part of the config

Needs to be merged after ([#11](https://github.com/Topsort/topsort.js/pull/11))

2024-07-31 12:33 UTC, jbergstroem commented on e2e/auctions.test.ts
> +        throw new Error("Global function `createAuction` is not available.");
can this happen? if not, strange logic to have in a test?

2024-07-31 12:34 UTC, jbergstroem commented on e2e/auctions.test.ts
> +        timeOut: 2000,
i would test a response that takes too long; so set timeout to 50ms

2024-08-13 10:21 UTC, barbmarcio commented
Can we land this?

2024-08-13 11:12 UTC, jbergstroem requested changes
I would still like to see at test that confirms that the request has timed out. Measuring how much time was spent is not really testing our logic for how to deal with the timeout.

2024-08-13 16:50 UTC, jbergstroem approved these changes

2024-08-13 16:54 UTC, merged