feat: add issue templates
Topsort/topsort.js pull request #29
Opened 2024-07-31 10:37 UTC by barbmarcio

2024-07-31 10:41 UTC, jbergstroem requested changes

2024-07-31 10:41 UTC, jbergstroem commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +      description: Provide screenshots if applicable.
this is an api, i don't think screenshots are helpful

2024-07-31 10:41 UTC, jbergstroem commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +title: "[BUG] "
no need to do this if the label is set

2024-07-31 10:41 UTC, jbergstroem commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +        Please fill in as much of the following form as you're able.
```suggestion
        Please complete the below form to help us look into the issue.
        
        Note: if you are looking for help, create a [discussion](https://github.com/Topsort/topsort.js/discussions) instead.
```

2024-07-31 10:41 UTC, jbergstroem commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +        - Browser [e.g. Chrome, Safari]
or runtime

2024-07-31 10:41 UTC, jbergstroem commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +      description: Provide details about the environment (OS, Browser, Version).
i think we can merge this with the above field

2024-07-31 10:41 UTC, jbergstroem commented on .github/ISSUE_TEMPLATE/2-feature-request.yml
> +title: "[FEATURE] "
lets lean on a issue label instead

2024-07-31 10:59 UTC, jbergstroem commented on .github/ISSUE_TEMPLATE/1-bug-report.yml
> +        - Browser [e.g. Chrome, Safari] (or runtime) [e.g. Node.js, .NET, Java]
```suggestion
        - Browser [e.g. Chrome, Safari] (or runtime) [e.g. Node.js, Deno, Bun]
```

2024-07-31 13:33 UTC, PabloReszczynski commented
Some example issue templates that I like:
- Bun's: https://github.com/oven-sh/bun/tree/main/.github/ISSUE_TEMPLATE
- Neovim: https://github.com/neovim/neovim/tree/master/.github/ISSUE_TEMPLATE

2024-08-02 15:53 UTC, jbergstroem approved these changes
We can always improve from here, LGTM.

2024-08-02 21:07 UTC, PabloReszczynski approved these changes

2024-08-05 11:50 UTC, merged